baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Bookish"
author = "Daniel Blezek"

[[menu.main]]
  name = "Introduction"
  weight = 1
  url = "/introduction"
  identifier = "introduction"

[[menu.main]]
  name = "Bookish menu item"
  weight = 5
  url = "/bookish"
  identifier = "bookish"
